/* Generated By:JJTree&JavaCC: Do not edit this line. OgnlParserConstants.java */
package org.ognl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OgnlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENT = 64;
  /** RegularExpression Id. */
  int LETTER = 65;
  /** RegularExpression Id. */
  int DIGIT = 66;
  /** RegularExpression Id. */
  int DYNAMIC_SUBSCRIPT = 67;
  /** RegularExpression Id. */
  int ESC = 71;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 73;
  /** RegularExpression Id. */
  int BACK_CHAR_ESC = 74;
  /** RegularExpression Id. */
  int BACK_CHAR_LITERAL = 76;
  /** RegularExpression Id. */
  int STRING_ESC = 77;
  /** RegularExpression Id. */
  int STRING_LITERAL = 79;
  /** RegularExpression Id. */
  int INT_LITERAL = 80;
  /** RegularExpression Id. */
  int FLT_LITERAL = 81;
  /** RegularExpression Id. */
  int DEC_FLT = 82;
  /** RegularExpression Id. */
  int DEC_DIGITS = 83;
  /** RegularExpression Id. */
  int EXPONENT = 84;
  /** RegularExpression Id. */
  int FLT_SUFF = 85;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinCharLiteral = 1;
  /** Lexical state. */
  int WithinBackCharLiteral = 2;
  /** Lexical state. */
  int WithinStringLiteral = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\",\"",
    "\"=\"",
    "\"?\"",
    "\":\"",
    "\"||\"",
    "\"or\"",
    "\"&&\"",
    "\"and\"",
    "\"|\"",
    "\"bor\"",
    "\"^\"",
    "\"xor\"",
    "\"&\"",
    "\"band\"",
    "\"==\"",
    "\"eq\"",
    "\"!=\"",
    "\"neq\"",
    "\"<\"",
    "\"lt\"",
    "\">\"",
    "\"gt\"",
    "\"<=\"",
    "\"lte\"",
    "\">=\"",
    "\"gte\"",
    "\"in\"",
    "\"not\"",
    "\"<<\"",
    "\"shl\"",
    "\">>\"",
    "\"shr\"",
    "\">>>\"",
    "\"ushr\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"instanceof\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"#this\"",
    "\"#root\"",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"@\"",
    "\"new\"",
    "\"$\"",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\r\"",
    "\"\\n\"",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "<DYNAMIC_SUBSCRIPT>",
    "\"`\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<ESC>",
    "<token of kind 72>",
    "\"\\\'\"",
    "<BACK_CHAR_ESC>",
    "<token of kind 75>",
    "\"`\"",
    "<STRING_ESC>",
    "<token of kind 78>",
    "\"\\\"\"",
    "<INT_LITERAL>",
    "<FLT_LITERAL>",
    "<DEC_FLT>",
    "<DEC_DIGITS>",
    "<EXPONENT>",
    "<FLT_SUFF>",
  };

}
